---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
      app: redis
  template:
    metadata:
      labels:
        service: redis
        app: redis
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: redis
      volumes:
      - name: config
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
