---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
      app: frontend
  template:
    metadata:
      labels:
        service: frontend
        app: frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "redis:6379"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: frontend
      volumes:
      - name: config
      containers:
        - name: frontend
          image: ncloud-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
