version: "3.8"
services:
  ncloud-frontend:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      consul:
    volumes:
      - type: volume
        source: counter-app-vol
        target: /code
  redis:
    image: "redis:alpine"
    networks:
      consul:
    ports:
      - target: 6379
        published: 6379

networks:
  consul:

volumes:
  counter-app-vol:

---
version: "3.7"

services:
  consul-server1:
    image: consul:1.9.3
    container_name: consul-server
    restart: always
    volumes:
      - ./server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

  consul-client:
    image: consul:1.9.3
    container_name: consul-client
    restart: always
    volumes:
      - ./client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"

networks:
  consul:
    driver: bridge
