version: "3.8"
services:
  sei-frontend:
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      counter-app-net:
    volumes:
      - type: volume
        source: counter-app-vol
        target: /code
  redis:
    image: "redis:alpine"
    networks:
      counter-app-net:

networks:
  counter-app-net:

volumes:
  counter-app-vol:
